apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: mealie-ngnix
  name: mealie-ngnix
  namespace: mealie
spec:
  ports:
  - nodePort: 31557
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
  type: LoadBalancer
